services:
  fake-gcs-server:
    attach: false
    image: fsouza/fake-gcs-server:latest
    ports:
      - 8080:8080
    networks:
      - discovery-network
    volumes:
      - ../data:/data
    command:
      [
        "-scheme",
        "http",
        "-port",
        "8080",
        "-external-url",
        "http://fake-gcs-server:8080",
        "-public-host",
        "fake-gcs-server",
        "-backend",
        "memory",
      ]
  fake-gcs-server-external:
    attach: false
    image: fsouza/fake-gcs-server:latest
    ports:
      - 5555:5555
    networks:
      - discovery-network
    volumes:
      - ../data:/data
    command:
      [
        "-scheme",
        "http",
        "-port",
        "5555",
        "-external-url",
        "http://localhost:5555",
        "-public-host",
        "localhost",
        "-backend",
        "memory",
      ]

  mongo:
    image: mongo:latest
    attach: false
    ports:
      - 27017:27017
    networks:
      - discovery-network
    volumes:
      - mongo-test:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          '''db.runCommand("ping").ok'' | mongosh mongo:27017/music-discovery-app-test --quiet',
        ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend.dev
      target: backend-test
    links:
      - mongo
    volumes:
      - type: bind
        source: ./apps/backend
        target: /app/apps/backend
    environment:
      NODE_ENV: test
    ports:
      - 3001:3001
    networks:
      - discovery-network
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
    #   interval: 10s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/frontend/Dockerfile
  #   volumes:
  #     - type: bind
  #       source: ./apps/frontend
  #       target: /app/apps/frontend
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - discovery-network
  #   depends_on:
  #     - backend

networks: # allow services to talk to each other while providing isolation from other docker container, running on the same host
  discovery-network:
    driver: bridge

volumes: # enable persistence of database data across container restart
  mongo-test:
    driver: local
