ARG NODE_VERSION=22.16.0
FROM node:${NODE_VERSION}-alpine

WORKDIR /app

# Copy base dependencies
COPY package.json yarn.lock tsconfig.json ./
COPY apps/backend ./apps/backend
COPY common/types ./common/types

# Install dependencies
RUN corepack enable && yarn install

EXPOSE 3001

CMD [ "yarn", "workspace", "backend", "test" ]
# RUN yarn workspace backend test